services:
  - type: web
    name: DRChoirBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python riri.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
